### ISSUE TITLE
Fetching notes based on the targetCode.

### ISSUE THREAD

**Issue by c7yrus** [genny-project/alyson#12]
Notes not being fetched when supplied with the correct targetCode at the endpoint.

1. Access Token is too long. 
2. CORS
3. POST Request to create a note.
4. GET - when you specify the source.

**Comment by adamcrow64** [comment]
This is currently working from local. 
CR=`curl -X GET "${url}/v7/notes/${key}"  --header "Authorization: Bearer $TOKEN" -H "accept: */*" -H "Content-Type: application/json"  --header 'Accept: application/json'  `
