### ISSUE TITLE
Sort by relevance needs to be handled by backend

### ISSUE THREAD

**Issue by sjlevens** [genny-project/alyson#22]
![image](https://user-images.githubusercontent.com/2309509/88988896-937a4e80-d31d-11ea-9e4d-1698d5e11935.png)
Currently we send this message to the backend and get no response.
We would like to receive an update SBE sorted by "relavance" whatever that means for the user (source code) and the SBE (target code)

**Comment by adamcrow64** [comment]
Need to think about this one..
