### ISSUE TITLE
Input Firstname and Lastname should save as Capitalised name.

### ISSUE THREAD

**Issue by sjlevens** [genny-project/alyson#29]

**Comment by adamcrow64** [comment]
This is interesting. The rules for them do capitalise them. Let's test to see what is going wrong

**Comment by adamcrow64** [comment]
This appears to be working?
entered the intern as bobby console
database shows:
PER_EEFA08AF-2618-46F5-907A-D88B8D2F887F
+------------+-------+----------------------------+---------------+-------------+----------------------------+------------------------------------------+
| dtype      | id    | created                    | name          | realm       | updated                    | code                                     |
+------------+-------+----------------------------+---------------+-------------+----------------------------+------------------------------------------+
| BaseEntity | 12379 | 2020-08-02 06:22:35.039000 | Bobby Console | internmatch | 2020-08-02 06:23:02.336000 | PER_EEFA08AF-2618-46F5-907A-D88B8D2F887F |
+------------+-------+----------------------------+---------------+-------------+----------------------------+------------------------------------------+
PRI_FIRSTNAME and PRI_LASTNAME all correct too.
And initials.

Any way to reproduce?

**Comment by adamcrow64** [comment]
Ah, this happens when more than one name is entered.
Should be easy to fix.

**Comment by adamcrow64** [comment]
testing fix

**Comment by adamcrow64** [comment]
fixed
