### ISSUE TITLE
Seperate Download column is appearing in Journals table. Might be COL_PRI_HAS_DOWNLOAD_LINK

### ISSUE THREAD

**Issue by ooanishoo** [genny-project/alyson#47]
![2020-08-05 at 9 04 am](https://user-images.githubusercontent.com/9260574/89353852-b1b7c400-d6fa-11ea-8bb2-fe248b4d719a.jpg)

**Comment by sjlevens** [comment]
If it is a COL we show a COL

**Comment by sjlevens** [comment]
Will have to think about how to hide a COL
